services:
  wavelet:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#      args:
    #        VERSION: v0.9.9
    image: ghcr.io/rain-kl/pixezsync:latest
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    ports:
      - "8061:8061"
    volumes:
      - ./uploads:/app/uploads
      - ./data/:/app/data
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
